source 'https://rubygems.org'

gem 'mysql2'
gem 'workflow'
gem 'haml-rails'
gem 'html2haml'
gem 'quiet_assets'
gem 'letter_opener', group: :development
gem 'faker'
gem 'devise'
gem 'jquery-ui-rails'
gem "cancan"
gem 'kaminari'
gem 'simple_form'
gem 'nested_form'
gem 'google-webfonts'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development