# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963d56684a82018d2a626e3f6fa318f8fbf0742eacae25ee2a2fa460d751be3bcec3cdbcc7e4bdc3b8115ad02aff65557c53aba3f23dbc56bbc1aae8ecde81d1

test:
  secret_key_base: 463864bb6367f298f8f1737fc1be213ff547ac888bb671a832d95b455059c2bdaa61435ca301b70d3232cc53dba7c4ce5f9ab4c52b9d2b319ffb07e5efc749e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
