# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a90fe34b325e64777fe9e73195890f4c8f2e830d3fa2d8b77b31afb0cdc0eafa96f4a98f847299da47f80e0223d0ec44da932aba4582cbccaf7a360499c00dc

test:
  secret_key_base: e88cf74760acc7bc0693efa75d67c9746731b0003380af91c929fd319b9d8bc419b9b5238979f38461d289c06ee6107e2fc691e139258b3d720e1e1715b66ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
